# permissions for end users to edit sectigoissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sectigoissuer-editor-role
rules:
- apiGroups:
  - certmanager.sectigo.oit.colorado.edu
  resources:
  - sectigoissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmanager.sectigo.oit.colorado.edu
  resources:
  - sectigoissuers/status
  verbs:
  - get
